
# Alacritty configuration

# Shell
[terminal.shell]
program = "/bin/bash"
args = ["-l"]

# Font
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "semibold" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 11.0

#----------------
# ini baris tema warna

#colors (Monokai)
[colors]
primary.background = "#272822" #ini mengahandle warna bagian warna background
#primary.foreground = "#66D9EF"
primary.foreground =  "#F8F8F2" # ini menghandle warna foreground, termasuk text disni, properti ini juga untuk memberi warna text

cursor.text = "#272822" #ini warna kalau text saat di block, 
cursor.cursor = "#F8F8F2" #ini warna untuk cursor

selection.foreground = "#AE81FF"
selection.background = "#AE81FF"

normal.black = "#272822"
normal.red = "#F92672"
normal.green = "#A6E22E"
normal.yellow = "#F4BF75"
normal.blue = "#66D9EF"
#normal.blue = "#00008B" #biru tua
normal.magenta = "#AE81FF"
normal.cyan = "#A1EFE4"
normal.white = "#F8F8F2"

bright.black = "#75715E"
bright.red = "#F92672"
bright.green = "#A6E22E"
bright.yellow = "#F4BF75"
bright.blue = "#66D9EF"
bright.magenta = "#AE81FF"
bright.cyan = "#A1EFE4"
bright.white = "#F9F8F5"


#-----------------------
# Keybindings
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"


[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

# Keybindings for scrolling
[[keyboard.bindings]]
key = "Up"
mods = "Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "Down"
mods = "Shift"
action = "ScrollLineDown"

# Window
[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10 }
decorations = "full"
opacity = 0.8
blur = true
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

# Scrolling
[scrolling]
history = 10000
multiplier = 3



# Cursor
[cursor]
style = { shape = "Block", blinking = "Always" }
thickness = 0.15

[terminal]
