
# Alacritty configuration

# Shell
[terminal.shell]
# program = "/bin/bash"
program = "/bin/zsh"
args = ["-l"]

# Font
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "bold Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 9

#----------------
# ini baris tema warna


# untuk warna silahkan ambil di folder warna lalu paste di sini

[colors]
#ini termasuk warna cursor 
# Colors (github)
# primary.foreground =  "#F8F8F2"
# primary.background = "#272822"
 # primary.background = "#1d2021" #ini hitam pekat
# "#010409" #ini rekomendasi hitam pekat juga

[colors.primary]
foreground = "#f0f3f6"
background = "#010409"

[colors.cursor]
text = "#010409"
# cursor = "#f0f3f6"
cursor = "#FFFF00"

[colors.selection]
text = "#f7c843"
background = "#ffffff"

[colors.normal]
black = "#7a828e"
red = "#ff9492"
green = "#26cd4d"
yellow = "#f0b72f"
blue = "#71b7ff"
magenta = "#cb9eff"
cyan = "#39c5cf"
white = "#d9dee3"

[colors.bright]
black = "#9ea7b3"
red = "#ffb1af"
green = "#4ae168"
yellow = "#f7c843"
blue = "#91cbff"
magenta = "#dbb7ff"
cyan = "#56d4dd"
white = "#ffffff"
#-----------------------



# Keybindings
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"


[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

# Keybindings for scrolling
[[keyboard.bindings]]
key = "Up"
mods = "Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "Down"
mods = "Shift"
action = "ScrollLineDown"

# Window
[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 5, y = 5 }
decorations = "full"
opacity = 0.8
blur = true
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

# Scrolling
[scrolling]
history = 10000
multiplier = 3


# Cursor
[cursor]
style = { shape = "Block", blinking = "Always" }

[bell]
animation = "Ease"

